; PlatformIO Project Configuration File
; Proyek PBLIF3-MC09: Rancang Bangun Perangkat Portable Visualisasi Status Deteksi Jamming Spektrum Maritim Berbasis ESP32
; Politeknik Negeri Batam - Semester III (IF316 IoT)

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
